- name: Install collectd
  apt: pkg=collectd state=present
  install_recommends: no
  tags:
      - dependencies

- name: Copy collectd configuration file into place
  template: src=etc_collectd_collectd.conf.j2 dest=/etc/collectd/collectd.conf
  notify: restart collectd

- name: Ensure collectd is started
  service: name=collectd state=started enabled=yes
