#!/bin/bash
set -o errexit
# Renew all live certificates with LetsEncrypt.  This needs to run at least
# once every three months, but recommended frequency is once a day.

certbot renew -q -c /etc/letsencrypt/cli.conf --pre-hook "service apache2 stop" --post-hook "service apache2 start" --deploy-hook "service dovecot restart"
