---
- name: Update apt cache
  apt: update_cache=yes
  tags:
    - dependencies

- name: Upgrade all safe packages
  apt: upgrade=safe
  tags:
    - dependencies

- name: Install necessities and nice-to-haves
  apt: pkg={{ item }} state=present
  with_items:
    - apache2
    - apt-transport-https
    - apticron
    - build-essential
    - debian-goodies
    - git
    - htop
    - iftop
    - iotop
    - molly-guard
    - mosh
    - python3-software-properties
    - python3-pip
    - ruby
    - screen
    - sudo
    - unattended-upgrades
    - vim
    - zsh
  tags:
    - dependencies

- name: timezone - Set localtime to UTC
  timezone:
    name: UTC

- name: Apticron email configuration
  template: src=apticron.conf.j2 dest=/etc/apticron/apticron.conf

- name: Create decrypted directory (even if encfs isn't used)
  file: state=directory path=/decrypted

- name: Set decrypted directory permissions
  file: state=directory path=/decrypted group=mail mode=0775

- name: Ensure locale en_US.UTF-8 locale is present
  locale_gen:
    name: en_US.UTF-8
    state: present

- import_tasks: encfs.yml
  tags: encfs
- import_tasks: users.yml
  tags: users
- import_tasks: apache.yml
  tags: apache
- import_tasks: ssl.yml
  tags: ssl
- import_tasks: letsencrypt.yml
  tags: letsencrypt
- import_tasks: ufw.yml
  tags: ufw
- import_tasks: security.yml
  tags: security
- import_tasks: ntp.yml
  tags: ntp
- import_tasks: google_auth.yml
  tags: google_auth
- import_tasks: postgres.yml
