---
# Defines tasks applicable for postgreSQL

- name: "[ENV] include OS static vars"
  include_vars: '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
  when: ansible_facts['distribution_release'] == 'focal'


- name: Install Postgres
  apt:
    name:
      - postgresql
      - "{{ _psycopg2 }}"
    state: present
  tags:
    - dependencies

- name: Set password for PostgreSQL admin user
  become: true
  become_user: postgres
  postgresql_user: name={{ db_admin_username }} password={{ db_admin_password }} encrypted=yes
